#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit

readonly dependencies=(pre-commit clang-tidy-11 clang-format-11 clang-apply-replacements-11 shellcheck)

function status() {
  printf "\\n\\n[Status] %s\\n" "$1"
}

function check_dependencies() {
  missing=0
  set +e
  for dependency in "${dependencies[@]}"; do
    if ! type "$dependency" >/dev/null 2>/dev/null; then
      ((missing++))
      echo >&2 "Missing dependency: $dependency"
    fi
  done
  set -e

  if ((missing)); then
    exit 1
  fi
}

function main() {
  status "Setting ignore-revs file..."
  git config blame.ignoreRevsFile .git-blame-ignore

  status "Checking dependencies..."
  check_dependencies

  status "Installing git hooks..."
  pre-commit install --install-hooks -t pre-commit -t pre-merge-commit \
    -t pre-push -t prepare-commit-msg -t commit-msg -t post-commit \
    -t post-checkout -t post-merge

  status "Dev environment is set up!"
}

main
